export const clerkAppearance = {
  variables: {
    colorBackground: "#0d121a",
    colorInputBackground: "#121a24",
    colorInputText: "#f4f7f5",
    colorText: "#f4f7f5",
    colorTextSecondary: "#a3afbd",
    colorTextOnPrimaryBackground: "#070a0f",
    colorPrimary: "#1A73E8",
    colorDanger: "#fb7185",
    borderRadius: "0.75rem",
  },
  elements: {
    rootBox: "w-full",
    card: "bg-[var(--surface)] border border-[var(--line)] shadow-[0_0_36px_rgba(26,115,232,.12)]",
    main: "bg-transparent",
    headerTitle: "text-[var(--ink)] font-display",
    headerSubtitle: "text-[var(--ink-muted)]",
    formFieldLabel: "text-[var(--ink-muted)]",
    formFieldInput: "h-11 rounded-xl !border-[var(--line)] !bg-[var(--surface-raised)] px-4 text-[var(--ink)] shadow-none transition-all placeholder:text-[var(--ink-faint)] focus:!border-[var(--neon-blue)] focus:ring-[var(--neon-blue)]",
    formFieldInputShowPasswordButton: "text-[var(--ink-faint)] hover:text-[var(--neon-blue)]",
    formFieldAction: "text-[var(--neon-blue)] hover:text-[var(--ink)]",
    formButtonPrimary: "h-11 rounded-xl bg-[var(--neon-blue)] px-4 font-semibold text-[var(--ink)] shadow-[0_0_20px_rgba(26,115,232,.2)] transition-all hover:bg-[var(--neon-blue)] hover:shadow-[0_0_28px_rgba(26,115,232,.3)] normal-case",
    socialButtonsBlockButton: "h-11 rounded-xl !border-[var(--line)] !bg-[var(--surface-raised)] px-4 text-[var(--ink)] shadow-none transition-all hover:!border-[var(--neon-blue)] hover:!bg-[var(--surface)] hover:shadow-[0_0_18px_rgba(26,115,232,.14)]",
    socialButtonsProviderIcon: "size-5",
    socialButtonsBlockButtonText: "font-medium !text-[var(--ink)]",
    dividerLine: "bg-[var(--line)]",
    dividerText: "text-[var(--ink-faint)]",
    identityPreview: "border-[var(--line)] bg-[var(--surface-raised)]",
    identityPreviewText: "text-[var(--ink)]",
    footer: "bg-transparent",
    footerActionText: "text-[var(--ink-muted)]",
    footerActionLink: "text-[var(--neon-blue)] hover:text-[var(--ink)]",
    alert: "border-[var(--line)] bg-[var(--surface-raised)] text-[var(--ink)]",
  },
} as const;
